### PR TITLE
Don't attempt a database failover without a known standby

### LINKED ISSUE #34: Failover with no standby takes 10 minutes to report that it failed
1) When successful, it looks like this:

```
[----] I, [2022-09-13T12:25:43.516108 #1609:96c8]  INFO -- evm: Updating servers cache to [{:type=>"primary", :active=>true, :host=>"10.0.2.10", :user=>"root", :dbname=>"vmdb_production"}, {:type=>"standby", :active=>true, :host=>"10.0.2.11", :user=>"root", :dbname=>"vmdb_production"}]
[----] E, [2022-09-13T13:00:44.246567 #1609:96c8] ERROR -- evm: Primary Database is not available for Rails production Config Handler. Starting to execute failover...
[----] I, [2022-09-13T13:00:44.306692 #1609:96c8]  INFO -- evm: Updating servers cache to [{:type=>"primary", :active=>true, :host=>"10.0.2.11", :user=>"root", :dbname=>"vmdb_production"}]
```

We have a primary and standby and everything is great and we failover to the standby when the primary fails.

2) When you have only a primary and no standby, we sit in the loop and wait 10 minutes to report it failed.

```
[----] I, [2022-09-13T13:00:44.306692 #1609:96c8]  INFO -- evm: Updating servers cache to [{:type=>"primary", :active=>true, :host=>"10.0.2.11", :user=>"root", :dbname=>"vmdb_production"}]
  |-evm-failover-mo,1608 /usr/bin/evm-failover-monitor
[----] E, [2022-09-13T14:00:49.703219 #1609:96c8] ERROR -- evm: Primary Database is not available for Rails production Config Handler. Starting to execute failover...
[----] E, [2022-09-13T14:10:50.251064 #1609:96c8] ERROR -- evm: Failover failed
```

If the current primary only knows about itself, there is nothing we can do.  We cannot failover automatically.  The user will have to manually configure the system to the correct database.  It shouldn't take 10 minutes to fail.

### PR DESCRIPTION
**Pull request by jrafanie**
(You might want to hide whitespace changes)

* Don't attempt a database failover without a known standby

Fixes #34

Related to https://github.com/ManageIQ/manageiq/pull/22115 https://github.com/ManageIQ/manageiq/pull/22116

I've tested https://github.com/ManageIQ/manageiq/pull/22116 along with https://github.com/ManageIQ/manageiq-postgres_ha_admin/pull/36 in the following scenarios:
* Failover to standby
* Failover with no standby (evmserverd exits with error, failover monitor skips failover and logs an error, manageiq-db-ready waits for the configured database to be accessible and restarts evmserverd when old db comes back up)
* Failback (failover from old standby back to primary) (primary was reintroduced as a standby before we fail back)

Instead of trying for 10 minutes, we fail quicker (up to 2 minutes based on the database check frequency)

```
Sep 19 16:57:02 app.localdomain systemd[1]: evmserverd.service: Main process exited, code=exited, status=1/FAILURE
Sep 19 16:57:02 app.localdomain systemd[1]: evmserverd.service: Failed with result 'exit-code'.
Sep 19 16:57:02 app.localdomain systemd[1]: evmserverd.service: Service RestartSec=100ms expired, scheduling restart.
Sep 19 16:57:02 app.localdomain systemd[1]: evmserverd.service: Scheduled restart job, restart counter is at 2.
Sep 19 16:57:02 app.localdomain systemd[1]: Stopped EVM server daemon.
Sep 19 16:57:02 app.localdomain systemd[1]: Starting ManageIQ DB Ready...
Sep 19 16:57:02 app.localdomain manageiq-db-ready[2788]: 10.0.2.11 5432 - not accepting connections
Sep 19 16:57:12 app.localdomain manageiq-db-ready[2788]: 10.0.2.11 5432 - not accepting connections
Sep 19 16:57:22 app.localdomain manageiq-db-ready[2788]: 10.0.2.11 5432 - not accepting connections
Sep 19 16:57:32 app.localdomain manageiq-db-ready[2788]: 10.0.2.11 5432 - not accepting connections
Sep 19 16:57:42 app.localdomain manageiq-db-ready[2788]: 10.0.2.11 5432 - not accepting connections
Sep 19 16:57:52 app.localdomain manageiq-db-ready[2788]: 10.0.2.11 5432 - not accepting connections
Sep 19 16:58:02 app.localdomain manageiq-db-ready[2788]: 10.0.2.11 5432 - not accepting connections
Sep 19 16:58:12 app.localdomain manageiq-db-ready[2788]: 10.0.2.11 5432 - not accepting connections
Sep 19 16:58:13 app.localdomain evm[2756]: ERROR -- evm: (PostgresHaAdmin#pg_connection) Failed to establish PG connection: could not connect to server: Connection refused
Sep 19 16:58:13 app.localdomain evm[2756]: ERROR -- evm: (PostgresHaAdmin#monitor) Primary Database is not available for Rails production Config Handler. Starting to execute failover...
Sep 19 16:58:13 app.localdomain evm[2756]: ERROR -- evm: (PostgresHaAdmin#execute_failover) Cannot attempt failover without a known active standby.  Please verify the database.yml and ensure the database is started.
Sep 19 16:58:13 app.localdomain evm[2756]: ERROR -- evm: (PostgresHaAdmin#monitor) Failover failed
```

Additionally, with https://github.com/ManageIQ/manageiq/pull/22115, we now will correctly sit and wait with the existing database.yml settings pointing to the failed database until manageiq-db-ready says it's up and running again...

```
# Continued from above:
Sep 19 16:58:22 app.localdomain manageiq-db-ready[2788]: 10.0.2.11 5432 - not accepting connections
Sep 19 16:58:32 app.localdomain manageiq-db-ready[2788]: 10.0.2.11 5432 - accepting connections
Sep 19 16:58:32 app.localdomain manageiq-db-ready[2788]: vmdb_production is up and running
Sep 19 16:58:32 app.localdomain systemd[1]: manageiq-db-ready.service: Succeeded.
Sep 19 16:58:32 app.localdomain systemd[1]: Started ManageIQ DB Ready.
Sep 19 16:58:32 app.localdomain systemd[1]: Started EVM server daemon.
```

### CODE REVIEW

**Review by Fryguy — APPROVED** [review]

File: lib/manageiq/postgres_ha_admin/failover_monitor.rb [hunk 1]
```diff
@@ -35,11 +35,11 @@ def monitor
...
-          if new_conn_info
-            handler.do_after_failover(new_conn_info)
-          else
-            logger.error("#{log_prefix(__callee__)} Failover failed")
-          end
+
+          logger.error("#{log_prefix(__callee__)} Failover failed") unless new_conn_info
+
+          # Upon success, we pass a connection hash, otherwise false
+          handler.do_after_failover(new_conn_info)
```
Comment (Fryguy) [inline lib/manageiq/postgres_ha_admin/failover_monitor.rb:42]: As discussed, let's leave this code as is.  It's weird to call `after_failover` when you haven't actually failed over. I could see adding a new hook in the old else condition called `failed_failover` or something, but since we don't have a use case on the caller, we can do that separately.

If we keep this hook code as is, then the only changes need on the server side are to remove the LinuxAdmin::Service stop and restart calls (which aren't need when systemd is doing all the work along with manageiq-db-ready.

File: lib/manageiq/postgres_ha_admin/config_handler.rb [hunk 2]
```diff
@@ -28,6 +28,7 @@ def do_before_failover
     end
 
     def do_after_failover(new_primary_conn_info)
+      # Upon success, we receive a connection hash, otherwise false
```
Comment (Fryguy) [inline lib/manageiq/postgres_ha_admin/config_handler.rb:31]: Also no need for this comment anymore
